### ISSUE TITLE
After Bootloader update Strato does not go into USB mode anymore

### ISSUE THREAD

**Issue by stratobugs** [fhorinek/BB#102]
After Bootloader update Strato does not go into USB mode anymore but stuck in charging mode, when connecting to Computer.
No USB-Symol on Strato, no connection to Computer possible

**Comment by fhorinek** [comment]
Just to be sure, are you using the right port for the usb connection? Can you try to flip the usb-c connector?

**Comment by stratobugs** [comment]
Yes sure I am on the right port. I have tryed it with the USB-C and the USB-A cable. Strato stucks in the charging mode.
Ich can either charge Strato by my laptop or charge my laptop by Strato. No USB-data connection/mode possible.

**Comment by ukeconsulting** [comment]
same issue, i had to reconfigure windows to use the mass storage driver with the strato, after it is working well.

**Comment by fhorinek** [comment]
Leaving this here for reference
https://www.youtube.com/watch?v=3Ls4A8wc1zI
