### ISSUE TITLE
GPS will not connect since update 171

### ISSUE THREAD

**Issue by atosmarkyp** [fhorinek/BB#113]
SInce update 171 my GPS will not connect, it was fine before the update.  I flew for over 3 hours yesterday, 2 flights and the longest one was over 2 hours and the GPS did not connect during both flights.  I checked the settings before I switched it off, GNSS was switched on and it's status was 'initialising'.

**Comment by atosmarkyp** [comment]
I will try reset tonight and report tomorrow.

**Comment by fhorinek** [comment]
Looks like it does this randomly with small probability. I was able to reproduce it on my device.

**Comment by vojtechBohman** [comment]
This issue does not happens only once after update.  It happened to me again when I wanted to fly. 
The software seems pretty buggy. You cannot never trust the device and I don't expect that from device for more than four hundred euro.

**Comment by fhorinek** [comment]
Please update to 177, there is a fix for the GNSS bug

**Comment by atosmarkyp** [comment]
This is fixed now, GPS connects and funtions working great.
