### ISSUE TITLE
fanet: no rise- / sink-value transmitted

### ISSUE THREAD

**Issue by rrunner83** [fhorinek/BB#114]
normally fanet status also contains information if you are rising or sinking -> this will be transmitted to other fanet devices.

in my case the track is transferred to Burnair.cloud and displayed on map with color code if sinking or rising.
feedback from Burnair developer was, that my track has 3021 transmitted dots, but only 29 including the rise- / sink-value.

i was not able to test with skytraxx 2.1, but I think also there we will not have the correct values.

strato fw = 171

**Comment by fhorinek** [comment]
Thank you for the report, the climb was missing from the message. Fixed in next release
