### ISSUE TITLE
Device not turning on / charging 

### ISSUE THREAD

**Issue by TobiasWust** [fhorinek/BB#115]
I have not use my strato for a month now. I wanted to give it another try today but it didn't even turn on.
I tried to charge but there is no charge indication and even after waiting for a couple hours it doesn't turn on again. I tried more than one charger.
Then I wanted to disconnect and reconnect the battery but it appears that the case is glued together an not meant to be opened.

**Comment by fhorinek** [comment]
thank you for the report
