### ISSUE TITLE
USB-Storage access

### ISSUE THREAD

**Issue by goodguy21** [fhorinek/BB#119]
Can't really access the Strato through USB(Ubuntu&Windows10 tested). Shows up as device, can open it with the file explorer, but tracklogs are gone (apart from two tracks from August). Also I can't change the files in the /config directory (wanted to restore the device after STRATO restored factory settings by itself).

fw171

**Comment by goodguy21** [comment]
Unfortunately I'm not that familiar with Linux Terminal.
Could you please tell me the exact line to call in terminal?
I know that the partition of my Strato is sdb1

**Comment by fhorinek** [comment]
try this
`sudo fsck /dev/sdb1`

**Comment by goodguy21** [comment]
Thank you! This seemed to be working.
Some corrupt parts were found, I changed then with fsck. This deleted the /config folder and created a new blank file called config. Fortunately I had a backup of all folders, pasted the old /config folder.
Now all pages are shown again and the custom Vario pattern seems to be working. I will verify it in flight today. Issue can be closed for now.
