### ISSUE TITLE
Menu button - white dot on screen

### ISSUE THREAD

**Issue by DefUnctUK** [fhorinek/BB#120]
Hi, when i press the menu button, all that happens is that a white dot appears on screen (as per the attached) - is this normal? Shouldn't the button call up a menu or something?[](ur
![IMG_2406](https://user-images.githubusercontent.com/31309707/140394346-d4394667-7a18-43c0-bf22-d371dee37137.jpg)
l)

**Comment by vojtechBohman** [comment]
It shows you on which page you currently are. if you specify more pages, you will see more dots.
