### ISSUE TITLE
Auto update V171->V177

### ISSUE THREAD

**Issue by vojtechBohman** [fhorinek/BB#121]
Update from Strato via WiFi does not work.
V171->V177

- connect to wifi
- Check FW
- Update FW
- Connection timeout! -> wifi is probably disconnected

[debug.log](https://github.com/fhorinek/BB/files/7550144/debug.log)

Wifi router runs without any problem. 

Seems no progress from #109. Just enjoying testing by customers.

**Comment by fhorinek** [comment]
Please update to 177 manually.
There are no fixes for wifi in 177 unfortunately.
We are aware of the problem and we will work on it in next update
