### ISSUE TITLE
Can anyone advise how to transfer the AGL files and how to access strato directory? Thanks

### ISSUE THREAD

**Issue by fhorinek** [fhorinek/BB#123]
Can anyone advise how to transfer the AGL files and how to access strato directory? Thanks

_Originally posted by @Ajaydee999 in https://github.com/fhorinek/BB/issues/105#issuecomment-971426861_

**Comment by fhorinek** [comment]
For now the AGL data needs to be downloaded manually from https://vps.skybean.eu/agl/ unzipped and placed in AGL directory on strato via USB cable

**Comment by Ajaydee999** [comment]
Reinstalled drivers (as if doing bootloader update) Get to DFU in FS mode and click connect - nothing happens. I believe it should show as mass storage at this point?

**Comment by fhorinek** [comment]
Are you using right port? The one with the USB symbol?
What is shown on the strato screen?

**Comment by Ajaydee999** [comment]
Yes the right port. Power connected to left. Screen is blank.

**Comment by fhorinek** [comment]
You do not need to go to the DFU mode. Just power off the strato and plug the cable to the right port.

**Comment by Ajaydee999** [comment]
Looks to be a PC fault and Not the Strato... Thanks for help so far.
