### ISSUE TITLE
Strato (v177) crashed during flight

### ISSUE THREAD

**Issue by kaja78** [fhorinek/BB#128]
Strato crashed during flight. Debug to file was enabled. I needed to reset it. 

Attaching files:
[debug.log](https://github.com/fhorinek/BB/files/7579845/debug.log)
[IGCs.zip](https://github.com/fhorinek/BB/files/7579849/IGCs.zip)

**Comment by fhorinek** [comment]
I am sorry for the trouble.

Can you please specify the crash
Does it crash with the white screen with the text on it?
Or does it become not responding? 
Or UI worked, but sound stop working?

**Comment by kaja78** [comment]
It crashed with white screen with some text on it. There was some hexadecimal error code and hint to reset the device.

And it was connected to XCtrack using BLE all the time. The tracklog from XCTrack: https://www.xcontest.org/cesko/prelety/detail:kaja78/20.11.2021/10:25

**Comment by kaja78** [comment]
You can see, there is missing baro data from 11:47:17 to 11:51:29 in XCTrack tracklog on XContext - so this should correspod to crash and reset times.

I also switched to external GPS in XCTrack between 12:11 - 12:19. You can observe there sudden difference in GPS altitude and probable rounding issue mentioned in #110 (the tracklog starts to be "square").

**Comment by ashghinn** [comment]
Mine (v177) has also crashed (about 6 times) while in flight, and while connected to XCTrack via BLE.
![image](https://user-images.githubusercontent.com/87761815/143323393-bc0aae40-a620-4729-8023-25344ad0f6de.png)

**Comment by ashghinn** [comment]
Mine (v177) has also crashed several times in similar circumstances - while flying and while connected to XCTrack via BLE

![image](https://user-images.githubusercontent.com/87761815/143323475-efd49082-2b44-48af-be6d-41a071338056.png)

**Comment by kaja78** [comment]
Yes, now I remember there was that INVSTATE message too.

**Comment by fhorinek** [comment]
Thank you for the report. I guess that this is screenshot from the video of head cam?
Is there any chance to recover the number in the first line after INVSTATE starting SP?

**Comment by ashghinn** [comment]
There are several frames in the sequence, but none very clear. It looks like
0x080_8_05F8, but could be
0x080_6_05F8 or
0x08080_S_F8
![Image8](https://user-images.githubusercontent.com/87761815/143493622-245c55dc-9e49-43a6-95bb-efbdaff280b5.jpg)
r

**Comment by fhorinek** [comment]
thank you I will try to locate the bug

**Comment by ashghinn** [comment]
This fault happens very frequently (almost every flight). But so far, it has only happened when flying and it seems to only happen when I am connected via bluetooth to XC Track. I've tried to simulate flight so I can get a clear picture of the fault code (difficult when flying!) but it doesn't seem to happen when I connect at home.

**Comment by chrisyeh889** [comment]
with V177, it crashed every flight. i return it to V171 for now.

**Comment by kaja78** [comment]
Today second flight with v177 and it crashed after few minutes. ![image](https://user-images.githubusercontent.com/6780745/145714847-1aba5634-c074-4e06-87c5-7e70688e54b4.jpeg)

**Comment by ashghinn** [comment]
Any news on this issue? 
I've been torn between wanting to help provide more info about this bug and needing a working vario. But with my setup 177 crashes almost every flight,  so I've given up and reverted to 171.

**Comment by fhorinek** [comment]
Yes the report helped greatly.
Now we are finalizing the build.
Release is scheduled Friday

**Comment by fhorinek** [comment]
Merging with #145
