### ISSUE TITLE
[FW177] Strato crashes when accessing the wifi vario editor

### ISSUE THREAD

**Issue by fliescher** [fhorinek/BB#130]
I connected to the Strato AP on my windows PC. As soon as I'm accessing the vario profile editor by the AP-IP address Strato crashes. Happens with both, Google Chrome and Microsoft edge.
Crash report screen:
![IMG20211125170835](https://user-images.githubusercontent.com/88840491/143474439-6aab2396-613a-4cd9-b98b-04736c2d2ac2.jpg)

**Comment by fhorinek** [comment]
thank you for the report

**Comment by fhorinek** [comment]
duplicate #125
