### ISSUE TITLE
completely dead strato

### ISSUE THREAD

**Issue by chrisyeh889** [fhorinek/BB#133]
i returned the firmware back to V171 2 days ago. today I thought i will give V177 another try. sadly it is dead during the update. the screen went black. the reset wont work. what should i do??

**Comment by ukeconsulting** [comment]
is it seen by the computeur when plugged in usb ? 
and in low level usb mode for changing the low level firmware?

**Comment by chrisyeh889** [comment]
no, nothing

**Comment by fhorinek** [comment]
Try to connect power to the left port and reset using the arrows

**Comment by chrisyeh889** [comment]
I did. no nothing

**Comment by chrisyeh889** [comment]
what should i do? send it back?

**Comment by fhorinek** [comment]
Sorry, yes please send request to info@skybean.eu and mention the link of the issue. Please keep invoice from post office, so we can refund the shipping cost

**Comment by chrisyeh889** [comment]
Thanks. Will do!

**Comment by fhorinek** [comment]
RMA
