### ISSUE TITLE
Agl - no TOPO data

### ISSUE THREAD

**Issue by IoannesCarolus** [fhorinek/BB#143]
I've downloaded the required data manually from https://vps.skybean.eu/agl/, unzipped and placed it in the AGL directory on strato (Fw208).
Nevertheless after a successful GPS-fix, the Agl-Widget always shows "no TOPO data".

**Comment by fhorinek** [comment]
I will add function to check/list the topo files loaded to stratí.

**Comment by fhorinek** [comment]
All the data (*.HGT) should be placed in the AGL directory, without any sub-directory

**Comment by IoannesCarolus** [comment]
Does FW232 already contain the feature <add function to check/list the topo files loaded to strato>?

Meanwhile I did a wipe but AGL is still not working.
The filesystem cannot be corrupted since copying/using my backed up .cfg files for page-layout from older firmware versions works splendid.

**Comment by fhorinek** [comment]
No it does not have this function yet.
I will be now changing the agl sub system for preparation to finalize the maps.
