### ISSUE TITLE
Issue - Network missing

### ISSUE THREAD

**Issue by IoannesCarolus** [fhorinek/BB#144]
I can't connect to my strato (fw208) in order to access the sound editor.

I've Internet that is provided via a LTE Router (Alcatel HH72) and in general following Networks are available.

- The green one is the default one (..._5G) , that is also used by my notebook.
![image](https://user-images.githubusercontent.com/96716536/147885129-56e42cb4-cb96-4151-862a-8393c6b80c45.png)

- Strato misses out on the green one and only finds the red one, which is not in use. (transmission distance <1m)
![image](https://user-images.githubusercontent.com/96716536/147885315-82dd4900-0cd3-4d60-84ae-929894b59612.png)

**Comment by fhorinek** [comment]
Unfortunately the esp32 module, used as wifi module support only 802.11 b/g/n  (2.4 GHz band). This is hardware constrains.

**Comment by IoannesCarolus** [comment]
Thx for the clarification!

@all: Walkaround = use the Strato's AP feature and access the Audio Editor via IP addrESS by Browser (IP see 'Network Info' in Strato)
