### ISSUE TITLE
Battery discharges even if it is powered off - Fw208

### ISSUE THREAD

**Issue by IoannesCarolus** [fhorinek/BB#146]
Yesterday I switched off the Strato with a remaining charge of 63%. Today I switched on showing me 0%.
This drain happened already the 3rd time, and the last 2 times with a fully wiped and newly flashed fw208.

**Comment by fhorinek** [comment]
This can only be caused by two factors.
Not updated bootloader (please check bootloader version in device info, should be 9)
or hardware fault.

**Comment by IoannesCarolus** [comment]
Bootloader Version is 9.
Since last time, there has been no further unintentional discharges. 
The charge level at the last switch-off is always more or less same at the switch-on.

**Comment by fhorinek** [comment]
ok I am closing this issue than, feel free to reopen it if the problem occurs
