### ISSUE TITLE
Vario sound "all the time rising"

### ISSUE THREAD

**Issue by MiraHead** [fhorinek/BB#15]
First flight after about 40 min. the vario sound started to indicate I was rising all the time - like there was 0.2 lift even when everything else was correctly showing around  -1.0 m/s.

I noticed that the flight time indicated that I have landed already, don't know if that happened automatically or I clicked the button somehow.

Restart didn't help with the issue, reset did.

Let me know if the debug to file option would help you with such problems. Does it store debug info for individual flights or will it be overwritten with next flight?

**Comment by fhorinek** [comment]
There is a problem with the communication buffer between stm and esp(sound co-processor). Sometimes the packet get droped and this is the result. I am currently looking for solution to this issue. 
debug log will be appended, it won't be overwritten

**Comment by fhorinek** [comment]
fixed in 139
