### ISSUE TITLE
FW232 display freeze

### ISSUE THREAD

**Issue by Basti3DB** [fhorinek/BB#153]
I updated the Firmware to FW323 and started playing around with the new thermal assist features.
But when i am in the page editor and want to add the "Thermal trace" widget, the display freezes.
Only a reset can get it back. The new widged was not placed.
After trying again, the same thing happend.

**Comment by fhorinek** [comment]
Thank you for the report, will check tomorrow

**Comment by thrull** [comment]
confirmed, only when adding not replacing another widget

**Comment by fhorinek** [comment]
You can try changing your firmware channel to devel and update firmware. It is fixed there

**Comment by Basti3DB** [comment]
I have done this update and now its fixed :)

**Comment by fhorinek** [comment]
Great

**Comment by fliescher** [comment]
[D293.0] adding the thermal trace widget to a page causes the device to crash.
Crash report will be sent to skybean shortly
