### ISSUE TITLE
OGN Tracking 

### ISSUE THREAD

**Issue by fhorinek** [fhorinek/BB#16]
Has anyone been able to successfully test the FANET/Flarm capabilities? I've tried by activating flight (manually) and walking as well as in idle (non flying) mode (Which now can be shown as walking or other safety options - very nice!)
But neither OGN nor Burnair (SkyNet) tracking have shown my device so far.
Wondering if there is still issues, I'm not in range or just not smart enough... :D

**Comment by fhorinek** [comment]
should work in 133, testet with OGN and SkyNet

**Comment by Skyhighpara** [comment]
Agreed, working, thank you!
