### ISSUE TITLE
[FW 236] altitude graph widget : why the white arrow?

### ISSUE THREAD

**Issue by ukeconsulting** [fhorinek/BB#187]
On the altitude graph, the white arrow has no point: it's big and doesn't show anything more than the graph itself.

**Comment by bubeck** [comment]
The arrow is the symbol for the glider. It helps the user understand, in which direction the graph is scrolling and gives a very fast visual feedback, whether he/she is sinking or raising over the last 30s.

**Comment by ukeconsulting** [comment]
is it possible to desactivate it ? i think 99% of the pilot will understand quickly how it works, but if you want to keep it, we should be able to hide it.

**Comment by bubeck** [comment]
@fhorinek you decide on how to proceed

**Comment by bubeck** [comment]
https://github.com/fhorinek/BB/pull/197

**Comment by ukeconsulting** [comment]
without the arrow it is top ! thanks :-)
