### ISSUE TITLE
[FW 236] no french file : how to find or computate to get .MAP  

### ISSUE THREAD

**Issue by ukeconsulting** [fhorinek/BB#192]
i went to https://strato.skybean.eu/map/ i could download Italia and monaco, but i am just in between and so i can not test easily the map widget in the 10 km betwe
 i went to osm but i didn't found .MAP files,  i found  .osm.pbf  .shp.zip  .osm.bz2 but regarding the size of the files, they are not the good one. 
 i don't know how to computate it myself the file for a country :-(

**Comment by thrull** [comment]
@ukeconsulting check it again, FR was just uploaded

**Comment by ukeconsulting** [comment]
ok thanks ! 
i began to wrote this yesterday night, i went to sleep and work and i posted it tonight without checking again ! 
i will try asap :-) 

but still i would be happy to know how to find them directly or to computate.

**Comment by fhorinek** [comment]
The guide will be available soon

**Comment by kolupaev** [comment]
+1 :) 

Waiting for US map, or happy to generate one if needed.
