### ISSUE TITLE
zoom for the map

### ISSUE THREAD

**Issue by Altgenug1** [fhorinek/BB#194]
I think it would be a good feature that when the map is displayed on a page, you can use the menu button for example to adjust the zoom factor. It will hardly be possible to go into the settings menu, then into the map menu and then into the zoom setting during flight.

**Comment by fhorinek** [comment]
Yes that is planned as shortcut for unused buttons in page mode

**Comment by bubeck** [comment]
https://github.com/fhorinek/BB/pull/198

**Comment by bubeck** [comment]
implemented in FW250
