### ISSUE TITLE
Update the FLARM license

### ISSUE THREAD

**Issue by IoannesCarolus** [fhorinek/BB#196]
At the beginning of the season, it is recommended to check the current licence status in the device (1) and, if necessary, to download a new licence file from the website of the respective device vendor. (2)

Regarding:
(1) "Strato Settings" -> FANET -> Settings -> FLARM expires dd.mm.yyyy in ddd days (I know, currently it is 447 days still valid)

(2) How is this solved for the Strato in the future?
E.g. XCTracer Max requires the user to manually update the FLARM license.

**Comment by fhorinek** [comment]
The newest FLARM licence is always packed to firmware update. The FLARM licence will be updated automatically with firmware update.
Updates are now quite frequent and they require computer or wifi connection.
Later there will be updates at least once per year to update licence, if nothing else will be added or fixed
