### ISSUE TITLE
powerlines on maps

### ISSUE THREAD

**Issue by theosch1** [fhorinek/BB#203]
![Unbenannt](https://user-images.githubusercontent.com/89224925/154689306-8a0b5fee-56ac-4797-9004-b37013397c95.png)
On the maps powerlines are red and cannot be distinguished from highways. Maybe these could be shown as dotted or dashed lines? The blu of lakes and rivers is hardly to be distinguished from the blu background. The railways are in light yellow bytheway

**Comment by thrull** [comment]
@theosch1 color scheme will updated very soon, there is a good chance that it will be today :-)

**Comment by fhorinek** [comment]
There is an update available, with much more readable colors.
We will revisit in the next update power-lines color since they are still red/black.

**Comment by fhorinek** [comment]
Fixed, main roads are now yellow/orange
![image](https://user-images.githubusercontent.com/9072684/155732164-7432df3a-b9ab-4a26-a2a4-1b0330caf4c6.png)

**Comment by ukeconsulting** [comment]
The red power lines are great !
I love it, it's really useful.
