### ISSUE TITLE
Flarm not working..

### ISSUE THREAD

**Issue by Ajaydee999** [fhorinek/BB#210]
cannot get device picked up by any flarm (ogn) receivers.. any advice welcomed...

**Comment by thrull** [comment]
@Ajaydee999 Can please show/describe Your configuration? 

I have succesully receive Strato signal on Other Strato and Stratux Device (FANET - well kinda OGN too).
- generally using FANET you dont need to have a GPS fix to send and receive signal.

I do not have real FLARM receiver to test it. FLARM != FANET

**Comment by Ajaydee999** [comment]
Thanks thrull.

There's not really anything to configure other than some very basic details. Fanet works on mine also however that's not the same as flarm.  Flarm is tx beacon only on the strato and should be able to be picked up by airfield receivers and visible online if they're configured to upload to ogn. Having been well within range of a couple of these I can only surmise that it doesn't work.

**Comment by Ajaydee999** [comment]
Thanks thrull.

There's not really anything to configure other than some very basic details. Fanet works on mine also however that's not the same as flarm.  Flarm is tx beacon only on the strato and should be able to be picked up by airfield receivers and visible online if they're configured to upload to ogn. Having been well within range of a couple of these I can only surmise that it doesn't currently work. Hopefully one of the developers can shed some light on this..

**Comment by Ajaydee999** [comment]
Thanks thrull.

There's not really anything to configure other than some very basic details. Fanet works on mine also however that's not the same as flarm.  Flarm is tx beacon only on the strato and should be able to be picked up by airfield receivers and visible online if they're configured to upload to ogn. Having been well within range of a couple of these I can only surmise that it doesn't work.

**Comment by ukeconsulting** [comment]
to my mind it is the same issue as https://github.com/fhorinek/BB/issues/57 
i think there is nothing to do in our side: i reseted the device and copied the config of the working device to the non working one, the flarm still doesn't see the non working one. 
both have FW242.

**Comment by Ajaydee999** [comment]
Many thanks for investigating this.

**Comment by Skyhighpara** [comment]
I can second this. I've setup a ground station, running GXAirCom (https://github.com/gereic/GXAirCom) on a Lilygo TTGO T-Beam (https://de.aliexpress.com/item/32875743018.html)
The station tracks FANET of my device without trouble, both in non-flying and flying mode correctly.
Gliders (sail planes) in the area are also picked up via Flarm (Legacy mode), consistently with OGN network, so the receiver side is working fine.

There is no FLARM signal coming from Strato though. None of the combinations of FANET&Flarm on/off, flying or grounded work to receive any signal.

Firmware: Testing channel 260
All tracking settings activated and different configurations tested.
Also tested 868MHz (Europe) and 915MHz receiving.

Let me know if I should try any other configuration/firmware.

**Comment by Ajaydee999** [comment]
Any progress with this issue at all?

**Comment by Skyhighpara** [comment]
As of 279.10 still no FLARM. 
Sad, since that was one of my main reasons to go for the device. 
No matter the setting (FLARM/FANET on/off combinations) or device state (flying/grounded) there is no FLARM signal.
I can only get FANET to work.

Tested with Lilygo T-Beam 868/915MHz version 
http://www.lilygo.cn/claprod_view.aspx?TypeId=62&Id=1281&FId=t28:62:28 
and GXAirCom
https://github.com/gereic/GXAirCom
35€ including decent GPS antenna.
This setup does see Skytraxx and all other kind of sailplanes/helicopters and FLARM users.

Please, **make FLARM working a priority**, I think that is an important safety improvement @fhorinek

**Comment by ElDevelish** [comment]
It works now with FW279.12!
Thank you so much, been waiting for that for a while :) 
.. It's such a relief to know local gliders will get warning now when they join my thermal :D
