### ISSUE TITLE
Split tracklog

### ISSUE THREAD

**Issue by vojtechBohman** [fhorinek/BB#221]
I would like to know why the tracklog was split?  
[debug.log](https://github.com/fhorinek/BB/files/8162832/debug.log)  
[Tracklog.zip](https://github.com/fhorinek/BB/files/8162838/Archive.zip)

Why the modified date is 1.1.1970 1:00?
![image](https://user-images.githubusercontent.com/82414966/156201834-53ac44b2-6612-47e1-a28c-79eb1f7eff9c.png)

**Comment by fliescher** [comment]
check for the auto landing settings. It's set to 18km/h by default which maybe is a little bit too high for e.g. a soaring flight. (Your .igc looks like a soaring flight and speed is below 15km/h in the last few seconds)

**Comment by vojtechBohman** [comment]
Aaaa, thank you :-)
