### ISSUE TITLE
Crash while in active flight and opening menu

### ISSUE THREAD

**Issue by Skyhighpara** [fhorinek/BB#23]
When the device is in flight mode and the menu is opened, the devices sometimes crashes, showing attached error message.
Cannot consistently reproduce it, might be connected to weak or no GPS signal.
![20210720_141800](https://user-images.githubusercontent.com/87414345/126322838-121a0525-5204-45bc-a6fb-42c4ad207d2d.jpg)

**Comment by fhorinek** [comment]
According to the error report it is connected to fanet distance formatting. Fixed in code, will be available in next release (>133)
