### ISSUE TITLE
Write flight logs as kmz/kml as well as igc (or instead of) 

### ISSUE THREAD

**Issue by kevinrobson17** [fhorinek/BB#253]
Any chance of getting the logs written out to kmz/kml files so they can be used in Google earth without manual conversion?
I dont know if the technical challenges (other the compressing kmz may be an issue on the device) but hopefully it is possible to dump to kml which I believe would be supported. 
Thanks

**Comment by kevinrobson17** [comment]
Is there any update on this? I'm still struggling to successfully convert the gpx files to google earth. 

Thanks

**Comment by ukeconsulting** [comment]
workaround : upload your new flights on xcontest and then download the kml
![image](https://github.com/fhorinek/BB/assets/17803490/9e936371-1b29-4d7f-99d6-749dc9346af7)

**Comment by bubeck** [comment]
I will take over. First implementation done. PR will be ready within a few days.

**Comment by kevinrobson17** [comment]
Nice one. Many thanks

**Comment by kevinrobson17** [comment]
Ho do I go about getting this feature? looks like #495 didn't quite work?
I also dont see any reason firmware updates available.
Thanks

**Comment by bubeck** [comment]
The code is finished and sucessfully merged with https://github.com/fhorinek/BB/pull/495. So you have to wait, until skybean releases the next firmware. I dont know, when this will be.
