### ISSUE TITLE
Lost my keypad

### ISSUE THREAD

**Issue by Altgenug1** [fhorinek/BB#270]
Hy service-team,

flew at Meduno yesterday. It was relatively warm (sun) and the glue under the keys seemed to have softened. After landing I realized that I had lost the keypad.
How can the repair be done? Should I send in the device?
![image](https://user-images.githubusercontent.com/13053081/163705641-12861d5e-0fac-412a-88ad-2d6b92e3c3e6.png)

**Comment by fhorinek** [comment]
Please send a request to info@skybean.eu we will send you a new one
