### ISSUE TITLE
D.271.0.0 is shown as R.271.0.0 in strato.

### ISSUE THREAD

**Issue by ukeconsulting** [fhorinek/BB#289]
Not really important but can pose problem when speaking about some firmware

![IMG_20220512_232629_397~2](https://user-images.githubusercontent.com/17803490/168171530-063355f7-8815-44ea-8f33-8e6b0faccff7.jpg)

**Comment by ukeconsulting** [comment]
![Uploading IMG_20220512_232629_397.jpg…]()

**Comment by fhorinek** [comment]
thank you, fixed in next devel
