### ISSUE TITLE
Can`t find the # anymore

### ISSUE THREAD

**Issue by Altgenug1** [fhorinek/BB#290]
Since 271 I can`t find the # at the keyboard any more
![strato 01](https://user-images.githubusercontent.com/13053081/168249393-13c4d636-e924-4efb-bd9e-9b09fbe9a05b.jpg)
![strato 02](https://user-images.githubusercontent.com/13053081/168249407-ed75b4c4-5868-417a-90e7-e8f71a2ccd6b.jpg)
?

**Comment by fhorinek** [comment]
It is between ? and <, but it is not drawn correctly. 
Fixed in next devel build, It will take time to move it to trough testing to the release

**Comment by Altgenug1** [comment]
Thx.
