### ISSUE TITLE
QNH change causes device crash [FW 133]

### ISSUE THREAD

**Issue by vojtechBohman** [fhorinek/BB#30]
Start the device, go to GNH widget, set the pressure and confirm.
Then the screen bus fault is shown.  

FW 133  
[debug.log](https://github.com/fhorinek/BB/files/6855931/debug.log)  
![BUS Fault](https://user-images.githubusercontent.com/82414966/126493096-c0110c4d-20ca-47ab-8d82-4389099d6076.jpg)

**Comment by fhorinek** [comment]
I was able to replicate the bug only by timeout-ing from the menu. Fixed in next release.
BTW thank you for the screenshot and debug.log file.
It makes my life a lot easier.
