### ISSUE TITLE
[R262] Initial fix in tracklog

### ISSUE THREAD

**Issue by fliescher** [fhorinek/BB#322]
Lately I'm getting an initial fix in the tracklog somewhere around Africa (0°N/S, 0° E/W) . Clearly that's a problem of the GPS not having a fix.
For me that's fine as in my opinion you better log more than needed than too few points. But maybe you find a clever way to doublecheck/validate the GPS data before start logging - although this means missing some information (baro-altitude) if you don't start logging in time.

However it's an enhancment and not crucial (to me)

**Comment by bubeck** [comment]
Tanks for the propsal. Fixed in https://github.com/fhorinek/BB/commit/ca019847a218a84740e4f05b90a90078fcc5e6e6
This is shipped with firmware 277 and newer. Please be aware, that "D" versions are for test only. Not production.
