### ISSUE TITLE
[D274]  AGL and Map folders limited to 1019 files

### ISSUE THREAD

**Issue by scottykarate1** [fhorinek/BB#332]
FW = 274
Hardware revision = 22
Windows 10 computer

After updating the firmware to D 274 from R 262, I am unable to load more than 1019 files into either AGL or Map folders on the Strato.  If I try to copy in the remainder of the files the Strato disconnects itself from the computer and then immediately reconnects itself. The Zip download of the US map has 1540 and the AGl has 1439 files.

**Comment by bubeck** [comment]
Exploration: Problem could be MTP or reliance-edge. I dont think that it is reliance-edge, as the file system is configured to offer 65535 inodes. I did not find anything to limit number of files of a specific directory.

        {SECTOR_SIZE_AUTO, SECTOR_COUNT_AUTO, 0, true, 0xFFFF, 10, "" }

So I assume, it is MTP related?

**Comment by bubeck** [comment]
Handing over to @fhorinek

**Comment by bubeck** [comment]
Extended to 102.400 files with 733cdcf345b2c57dd457c1fdc2f0f62cc9fde3a8.
Should be fixed in next firmware release.
