### ISSUE TITLE
Fix 00008200: BUS_FAULT, BFARVALID, PRECISERR in load_map_file (tile.c:730)

### ISSUE THREAD

**Issue by fhorinek** [fhorinek/BB#335]
### Reason ###

00008200: BUS_FAULT, BFARVALID, PRECISERR

### Link to App Center ###

* [https://appcenter.ms/users/fhorinek/apps/Strato/crashes/errors/1803249984u](https://appcenter.ms/users/fhorinek/apps/Strato/crashes/errors/1803249984u)

**Comment by bubeck** [comment]
I dont understand this issue. The stack trace shows the BUS_FAULT at

https://github.com/fhorinek/BB/blob/debb458e18ec49fcfa3966cc1d26b9d50635a701/BB3/App/gui/map/tile.c#L730

However, I can not imagine, why this should lead to a problem. Even if ps_malloc would return some garbage for map_cache, then still calling ps_free should be no problem. Could there be a problem with the stack trace?
