### ISSUE TITLE
Fix 01000000: USAGE_FAULT, UNALIGNED in db_query_int (db.c:116)

### ISSUE THREAD

**Issue by fhorinek** [fhorinek/BB#336]
### Reason ###

01000000: USAGE_FAULT, UNALIGNED

### Link to App Center ###

* [https://appcenter.ms/users/fhorinek/apps/Strato/crashes/errors/687115294u](https://appcenter.ms/users/fhorinek/apps/Strato/crashes/errors/687115294u)

**Comment by bubeck** [comment]
Stacktrace is:

https://github.com/fhorinek/BB/blob/debb458e18ec49fcfa3966cc1d26b9d50635a701/BB3/App/config/db.c#L116
https://github.com/fhorinek/BB/blob/debb458e18ec49fcfa3966cc1d26b9d50635a701/BB3/App/fc/vario.c#L114

So it seems, that either "value" is invalid (which seems hard to get invalid) or the data read from database is invalid and atoi fails. However in that case, I would expect atoi to be at the top of the stacktrace.
