### ISSUE TITLE
Fix 00000400: BUS_FAULT, IMPRECISERR in vario_profile_load (vario.c:114)

### ISSUE THREAD

**Issue by fhorinek** [fhorinek/BB#338]
### Reason ###

00000400: BUS_FAULT, IMPRECISERR

### Link to App Center ###

* [https://appcenter.ms/users/fhorinek/apps/Strato/crashes/errors/3031076155u](https://appcenter.ms/users/fhorinek/apps/Strato/crashes/errors/3031076155u)

**Comment by BoehniM** [comment]
Can you give us, who are not that familiar with IT, a brief information what this means. Thx

**Comment by bubeck** [comment]
All these 'Fix' issues are created automatically on Strato wherever it crashes and the user acknowledges uploading. This helps developers to see, what problem we have and give them hints on how's to fix them.

**Comment by BoehniM** [comment]
Thx for that clarification. Hope to see some stable update for common users quickly.
