### ISSUE TITLE
Switching "Use 24h time" off freezes device

### ISSUE THREAD

**Issue by scottykarate1** [fhorinek/BB#340]
FW = 276
Hardware revision = 22

Device when turning off the Use 24h time
Settings > Units > Use 24h time.  Turning this off will reliably freeze the device.
Hard reboot has to be done to get it to work again.

**Comment by bubeck** [comment]
I can confirm this. However, in my case I had to turn device off and on to see the crash. During boot I first get the lock icon and by pressing middle button screen keeps white and does not continue.
