### ISSUE TITLE
Fix 02000000: USAGE_FAULT, DIVBYZERO in tile_align_to_cache_grid (tile.c:649)

### ISSUE THREAD

**Issue by fhorinek** [fhorinek/BB#342]
### Reason ###

02000000: USAGE_FAULT, DIVBYZERO

### Link to App Center ###

* [https://appcenter.ms/users/fhorinek/apps/Strato/crashes/errors/1280617961u](https://appcenter.ms/users/fhorinek/apps/Strato/crashes/errors/1280617961u)

**Comment by bubeck** [comment]
Problem found. Fix is on the way.
