### ISSUE TITLE
garbage data in top of the igc files

### ISSUE THREAD

**Issue by Taka-New** [fhorinek/BB#349]
Hello, 

Garbage data like following are inserted sometimes in top of the igc files.
Attached is an example igc file.
I posted because I couldn't find the same issue in the past issues list.

Thanks.

B0209010000000S00000000WV0060700000
B0209020000000S00000000WV0060800000
B0209030000000S00000000WV0060700000
B0209040000000S00000000WV0060700000
B0209050000000S00000000WV0060700000
B0209060000000S00000000WV0060700000
B0209070000000S00000000WV0060700000
[2022.08.06 02.10.igc.zip](https://github.com/fhorinek/BB/files/9481683/2022.08.06.02.10.igc.zip)

**Comment by bubeck** [comment]
As a first guess:
* the data is from the pre flight buffer
* It shows invalid GPS coordinates. This means, there was no GPS fix.

Question: could it be, that you turn on Strato just seconds before the flight and you start without having a GPS fix (for some time)?

Proposal: Enhance IGC logger to skip GPS data with nox fix.

**Comment by Taka-New** [comment]
Bubeck-san, Thank you for your proposal.
