### ISSUE TITLE
[D276] Not valid tracklogs

### ISSUE THREAD

**Issue by vojtechBohman** [fhorinek/BB#352]
The tracklogs from this version are not accepted on the XContest - not valid.
Why?
![Screenshot 2022-09-13 at 17 39 26](https://user-images.githubusercontent.com/82414966/189946183-acb52ad6-1225-4cb7-8f40-e5c3f88aea5c.png)  
https://www.xcontest.org/world/en/flights/detail:vojtechBohman/13.9.2022/14:36  
[2022.09.13 14.39.igc.zip](https://github.com/fhorinek/BB/files/9558673/2022.09.13.14.39.igc.zip)

**Comment by ElDevelish** [comment]
G-record invalid probably. Been happening on mine for a while too, same firmware.
On that note: Flarm still not working and the promised airspaces still missing since march. 
I just kinda gave up on the device.

**Comment by bubeck** [comment]
Yes. If you look at your IGC you see 

    HFRFWFIRMWAREVERSION:D.276.0.0

that you are using a "D" Development version. It does not have a private key, so IGC is not signed

    HFFRSSECSUSPECTUSEVALIPROG:This file is not valid. Private key not available!

Please use "R" version for signed IGCs.

**Comment by vojtechBohman** [comment]
@bubeck  Could you tell me where is written this information? In which manual?

I am trying to help with the development that I am trying dev version but there is no peace of communication from developers.

Auto update in the device doest not work - #354
