### ISSUE TITLE
[D276] Update from dev to release freezes

### ISSUE THREAD

**Issue by vojtechBohman** [fhorinek/BB#354]
Based on your info that I should use release I tried to use the function in Strato.

1. Change to release version
2. Click to download FW 
![image](https://user-images.githubusercontent.com/82414966/190118961-790c1364-b0cc-4142-8eb0-bd0b32b0a8d0.png)
4. It is not possible to download
![image](https://user-images.githubusercontent.com/82414966/190119015-98284a6d-a03b-44ea-a80e-5986edb8d0fe.png)
6. Vario froze several times - crash report sent by device

**Comment by fliescher** [comment]
As a workaround you should try this:
"Alternatively you can download the update file from https://strato.skybean.eu/fw/ and place it in the stato root directory. Make sure that the file name is strato.fw (no numbers in bracket behind)" 
(Copied from the Strato deep dive)

**Comment by bubeck** [comment]
You are running D276, which is a development firmware in version 276. As you requested the firmware channel "release" it downloads the latest release firmware, which is version 262 (much older). A (automatic) downgrade is not supported (only upgrade). 

So you have to do a manual downgrade as specified above from fliescher.

But please keep in mind, that there are huge differences between 276 and 262, especially the file system. So by going back you will lose all data and logs stored on the device.
