### ISSUE TITLE
 when updating firmware, pilot.cfg file is replaced with the one inside the new firmware 

### ISSUE THREAD

**Issue by ukeconsulting** [fhorinek/BB#36]
it is quite annoying, it even doesn't use the one in system\assets\defaults\pilots

(firmware 138)

**Comment by ukeconsulting** [comment]
when updating firmware, time parameter like summer time and timezone are erased.

**Comment by ukeconsulting** [comment]
seems working well now: FW136 to FW145 i didn't have to put back the pilot.cfg after update and it keeped daylight config

**Comment by fhorinek** [comment]
Great thanks for report. I think it was caused by entering bootloader (eg OTA update) without saving the settings. (Fixed now)
