### ISSUE TITLE
Airspace

### ISSUE THREAD

**Issue by BoehniM** [fhorinek/BB#378]
As you included airspace as an option when can we expect the library to make it work?

**Comment by fhorinek** [comment]
you can use standard openair format, https://airspace.xcontest.org/

**Comment by ElDevelish** [comment]
Any special filename or folder required for them to be loaded?

**Comment by fhorinek** [comment]
Sorry you need to create dir `airspace` and put the files there. Fixed in #380

**Comment by BoehniM** [comment]
Displaying works! Let's see if warnings as well...

**Comment by fhorinek** [comment]
Warnings are not yet implemented, just display

**Comment by Skyhighpara** [comment]
Currently seems to support very small files only;
Germany-Austria-Italy fails at 83% loading; when I included France and Switzerland before it stopped at 48%.
Single countries for now then I guess.

**Comment by BoehniM** [comment]
You tried uploading individually? Because maybe then you can just activate them on the Strato as needed, can’t you?

**Comment by Skyhighpara** [comment]
> You tried uploading individually? Because maybe then you can just activate them on the Strato as needed, can’t you?

Sure. That's exactly what I said; Single countries for now.
Just prefer to update all at once instead of having to generate and update them all individually - which is for example already possible on a 10 year old Kobo running some outdated version of LK8000. But not on a modern device where 2MB text file is currently too large to handle ;)

**Comment by bubeck** [comment]
Thanks for your support and patience. This is just to give you an update on the current status. 

Fero has optimized loading airspaces. It is now faster and more stable. It has had problems with some files/countries, that either hat errors or special cases, that have not been tested before. It should now be more stable.

**Comment by bubeck** [comment]
Let us know, if problem still persist
