### ISSUE TITLE
WiFi & Bluetooth

### ISSUE THREAD

**Issue by chrisyeh889** [fhorinek/BB#385]
WiFi and Bluetooth are fine on D276, but not working after D278 and D279. back to D276 now.

**Comment by ukeconsulting** [comment]
wifi OK on  strato T.279.21.0

BT NON OK on  strato T.279.21.0 :
- smartphone android 11 : strato connected after many try "can't communicate with Strato." then it connect again without problem as a speaker 
- chromebook : impossible to see the strato
- windows 10 pro : no pb to connect as a speaker

**Comment by fhorinek** [comment]
Thank you for the report. 

Can you connect while you are in Strato bluetooth settings?
You need to be in Strato bluetooth settings, when you are pairing, only then it is visible to outer devices (SPP and A2DP).

Clarifications:
`Strato_XXXXXX` is for A2DP (speaker) or SPP (telemetry), you should be able to pair from android settings. 
`Strato_XXXXXX LE` is only for BLE (telemetry) and you need to connect to it via app (e.g. XCTrack)

RE note: yes this is problem with old bootloader, after next update (or reapplying T.279.21.0 it will show correct version.

**Comment by ukeconsulting** [comment]
sorry for the delay, i didn't see the answer.

On T.279.21.0  & R.279.21.3 & D.285.0.0  i see some wifi but not the hotspot of my smartphone, my computer is well connected to the hotspot (hence i can post here). 
 
 
 on R.279.21.3 & D.285.0.0  i don't have a problem yet with bluetooth (i just made some basic tests and all seems ok : vario from BT ok sound from BT ok )

**Comment by fhorinek** [comment]
Is your hotspot 5GHz? Strato support only 2.4GHz

**Comment by chrisyeh889** [comment]
Dear Harinek,
I am using 2.4GHz hotspot.
It is OK now. I found out after firmware update, the wireless is acting
weird. I have to restart 1 or 2 times, after that it will be normal.
anyway, it is not an issue anymore.

FLYTaiwan Paragliding
Yeh, Chris
Cell +886 (0)910704354
***@***.***
***@***.***
http://www.flytaiwanpara.com/
http://www.faccebook.com/FlyTaiwanParagliding/


František Horínek ***@***.***> 於 2022年12月27日 週二 下午5:52寫道：

**Comment by ukeconsulting** [comment]
> Is your hotspot 5GHz? Strato support only 2.4GHz

I checked and I didn't know my phone was providing only 5GHz wifi, with 2,4GHz I get the wifi on strato from my phone too. 
Thanks 👍
