### ISSUE TITLE
How is igc signing handled?

### ISSUE THREAD

**Issue by JEK58** [fhorinek/BB#4]
How is igc signing handled in this open source environment?
Will custom code simply create invalid igc files?

**Comment by bubeck** [comment]
I am not the author but a contributor. if you take a look at the repository of the former Skydrop repo at GitHub you will see that the Open source Version also creates igc files. however there is no private key used so this file is not valid for records.

**Comment by fhorinek** [comment]
It is handled similar to skydrop. IGC implementation will be open source, private key won't.
