### ISSUE TITLE
[T279] Device wipe

### ISSUE THREAD

**Issue by vojtechBohman** [fhorinek/BB#404]
Can you explain how to wipe the device?
There are 2 different procedures - one in doc, second in YouTube video and none of them work.
I have 2 System and system folders in  Strato and I am not able to delete them. It froze every time I try that.

![obrazek](https://user-images.githubusercontent.com/82414966/197257221-d17a5734-577f-43f7-9674-1f5a05b66b70.png)

**Comment by fhorinek** [comment]
This method should work.
https://youtu.be/8RftdomWoWA
Can you see the count down?

**Comment by vojtechBohman** [comment]
No, I tried it several times.
See my tries: https://youtu.be/HYf9h3fQl1M

**Comment by vojtechBohman** [comment]
I was wrong. I tried it again. 
Released the middle button when message is shown and it worked.
