### ISSUE TITLE
Time stamp in flight log doesn't match time of the flight.

### ISSUE THREAD

**Issue by scottykarate1** [fhorinek/BB#410]
HW V 22.  FW V 283
Date and time are correct when viewed in the D&T section of the System screen. All switches are green and time zone is UTC-8:00. However, when viewing a flight log of a flight at 5:00 PM PST, the time stamp for the flight starts at 0:00 AM.
A track viewer (Sportstracklive.com) I uploaded the IGC file to has the correct time stamp. on it. So it might be how/where the log viewer is getting it's time info.
Let me know if you need any files from the device

**Comment by fliescher** [comment]
afaik .igc files need to contain the date/time in UTC format to be FAI-compliant...

**Comment by fliescher** [comment]
Oh, I think I misunderstood the problem, sorry. So .ich logging is correct but the flightlog-viewer inside the Strato is displaying the wrong time?!

Sorry 😇

**Comment by bubeck** [comment]
You are probably right. I will take a look at the code and fix it

**Comment by scottykarate1** [comment]
> Oh, I think I misunderstood the problem, sorry. So .ich logging is correct but the flightlog-viewer inside the Strato is displaying the wrong time?!
> 
> Sorry 😇

Yes, that is the issue.

**Comment by bubeck** [comment]
IGC file spec:

"B" record must be in UTC and in addition there must be a "HFTZNTIMEZONE:+2.00" indicating the timezone relative to UTC.

**Comment by bubeck** [comment]
> HW V 22. FW V 283 Date and time are correct when viewed in the D&T section of the System screen. All switches are green and time zone is UTC-8:00. However, when viewing a flight log of a flight at 5:00 PM PST, the time stamp for the flight starts at 0:00 AM. A track viewer (Sportstracklive.com) I uploaded the IGC file to has the correct time stamp. on it. So it might be how/where the log viewer is getting it's time info. Let me know if you need any files from the device

Just to make sure, that the bug is fixed, could you please provide the igc? You can send me via email at tilmann AT bubecks.de

**Comment by scottykarate1** [comment]
Here you go    On Wednesday, November 2, 2022 at 12:09:56 PM PDT, Dr. Tilmann Bubeck ***@***.***> wrote:  
 
 



HW V 22. FW V 283 Date and time are correct when viewed in the D&T section of the System screen. All switches are green and time zone is UTC-8:00. However, when viewing a flight log of a flight at 5:00 PM PST, the time stamp for the flight starts at 0:00 AM. A track viewer (Sportstracklive.com) I uploaded the IGC file to has the correct time stamp. on it. So it might be how/where the log viewer is getting it's time info. Let me know if you need any files from the device


Just to make sure, that the bug is fixed, could you please provide the igc? You can send me via email at tilmann AT bubecks.de
