### ISSUE TITLE
The Show on Map screen doesn't show the flight path graphic

### ISSUE THREAD

**Issue by scottykarate1** [fhorinek/BB#411]
HW V 22.  FW V 283
The Show on Map screen doesn't show the flight path graphic.   It does show the altitude graphic.
This worked back in FW Version 281.
Let me know if you need any files from the device.

**Comment by bubeck** [comment]
Could you please send the igc file via email to tilmann AT bubecks.de? Thanks!

**Comment by bubeck** [comment]
Not reproducible, missing IGC
