### ISSUE TITLE
[R.279.23.2] Flight statistics sort

### ISSUE THREAD

**Issue by vojtechBohman** [fhorinek/BB#438]
What kind of sort are you using in flight statistics?
Seems to be random?

![20230111_210320](https://user-images.githubusercontent.com/82414966/211932021-a8306310-d982-4a79-803f-6e7b380fc71e.jpg)

**Comment by bubeck** [comment]
You maybe right. i will check

**Comment by bubeck** [comment]
It is currently sorted according to "date" and not "name". So I assume that your directories have date stamps in the order of your screenshot. I think a better way would be to sort according to "name", as the IGC file names have a sortable name.
