### ISSUE TITLE
Feature plan

### ISSUE THREAD

**Issue by vojtechBohman** [fhorinek/BB#464]
Hi, 

As a user of strato I would like to know what is the plan with feature implementation. What is happening right now, what is plan?
Some document with description has existed but it has disappeared and there is no new information.

Could you also please comment in what state are the features mentioned on the product page:
Connectivity
... Strato is connected via Wi-Fi to your phone or home network for automatic tracklogs upload. Maps, terrain and airspace data are always up-to-date without need for a computer.
Energy Management
Strato has two USB-C ports, so in the air, energy can flow from the power bank through Strato to the phone with simultaneous data tethering. Quick Charge technology is able to provide huge amounts of energy for faster charging, an hour while driving to takeoff is enough.

Will strato warm pilot when there is some cables or obstacles ie in Alps?

Thx for your time.

**Comment by fhorinek** [comment]
I am currently working on the automatic map + agl download, airspace from xcontest will follow.
expect a testing release for it next week, followed by bug fixing and release.
You will be able to get the igc files via wifi from strato, no automatic update yet in next release.

Strato displays lifts or power cables on the map.

**Comment by vojtechBohman** [comment]
Two weeks without release and progress. Whats happening?

Still missing answer for question:
Energy Management
Strato has two USB-C ports, so in the air, energy can flow from the power bank through Strato to the phone with simultaneous data tethering. Quick Charge technology is able to provide huge amounts of energy for faster charging, an hour while driving to takeoff is enough.
