### ISSUE TITLE
put default unique name on networks (BT & wifi) and as a usb drive.   

### ISSUE THREAD

**Issue by ukeconsulting** [fhorinek/BB#47]
i have 2 stratos and it is difficult for me to know which one is which one from computer.
i tried to rename when usb drive but it keep the default one.  

not the fanet but the serial on the name (or let the choice to the user, i don't want my fanet number be broadcasted to everybody) 

nowadays both are called:
usb drive = Strato
wifi = Strato_10076480 (could be manually changed)
BT = Strato

**Comment by ukeconsulting** [comment]
nowadays both are called:
usb drive = Strato
wifi = Strato_10076480
BT = Strato

**Comment by fhorinek** [comment]
Planned:
usb drive = change only when disk label is empty or after the sd card format
wifi, bt = will use device_name, that could be changed manually

BTW the number in device name is shortened device id not the fanet number

**Comment by ukeconsulting** [comment]
with friends we like to hijack BT devices (even during flights), with strato it is not possible to hijack BT music when it is already playing music but it is still possible to hijack when no phone is connected. 
is it possible to add a BT confirmation menu (with 20s automatic refusal) on strato when a device try to connect to strato with BT ? so no hijack is possible.

**Comment by ukeconsulting** [comment]
FW166: that works, i can see names of both devices on android smartphone and windows laptop.
at first i successfully saw only one only on windows. after several BT switch off, power switch off, reset, i could see both strato on both devices (and connection was ok)

**Comment by fhorinek** [comment]
Fixed
