### ISSUE TITLE
FANET Radar incorrect location. 

### ISSUE THREAD

**Issue by kolupaev** [fhorinek/BB#497]
Hi. 

Fanet radar seems to display location incorrectly. I was flying with a friend, transmitting with skytraxx, however his position was always shown farthest W from me.

See debug log and screenshot attached. 

[debug.zip](https://github.com/fhorinek/BB/files/12141449/debug.zip)
![20230721_174712](https://github.com/fhorinek/BB/assets/533414/8777ea62-2bbd-485b-a58a-1bbbc4084097)

**Comment by alexalder101** [comment]
I've had the same issue. Also when changing the Fanet zoom the position doesn't change accordingly. Firmware R279.23.3

**Comment by kolupaev** [comment]
Funny enough, it is reproducable only to he left of the pond (or to the bottom of the equator) 
Fixed in https://github.com/fhorinek/BB/pull/506
Also added a feature to forward Fanet data to XCTrack, so it could be visualized on the phone. 

@bubeck  Could you take a look at the PR please? 

![Screenshot_20231119_193039_XCTrack](https://github.com/fhorinek/BB/assets/533414/2d3ea3ef-72a7-45be-adda-c86e0112b3f8)
![20231117_211134](https://github.com/fhorinek/BB/assets/533414/1e9c78db-f054-4008-b81a-5d90c548f131)
