### ISSUE TITLE
Vario audio does not accurately represent climb rate

### ISSUE THREAD

**Issue by ashghinn** [fhorinek/BB#52]
Vario audio is unreliable at reporting climb rate. Very often (most thermals) the audio gets stuck at a fixed frequency and pitch despite considerable changes in climb rate (fw139).  It tends to start ok when a climb begins, but nearly every time it seems to lock onto a certain pitch/frequency. So as the climb weakens, the vario audio continues at the previous level, until the min climb threshold is reached, and the audio stops altogether. I've played around a bit with the audio profiles, (and accelerometer gain) but neither seems to make any difference to this issue, and in flight this issue remains a pretty constant problem.

The audio also sometimes continues to report a steady climbrate when no longer climbing. If this happens it is usually impossible to stop it. Even by switching off the instrument.  i recall there was a bug report about this a while back, but this still seems to happen.

**Comment by fhorinek** [comment]
confirmed, fix in progress

**Comment by ashghinn** [comment]
Cheers!Ash From: František HorínekSent: 05 August 2021 13:16To: fhorinek/BBCc: ashghinn; AuthorSubject: Re: [fhorinek/BB] Vario audio does not accurately represent climb rate (#52) confirmed, fix in progress—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fhorinek** [comment]
changed how tones are generated to prevent ring buffer issues. Now I am unable to replicate the bug
