### ISSUE TITLE
Some insight into development

### ISSUE THREAD

**Issue by vojtechBohman** [fhorinek/BB#53]
Hi,
We cannot see what's happening in the development.
The google document where are all features and widgets is not updated - https://docs.google.com/spreadsheets/d/1SBfl7NBxJKt3wLTpe-ecjcOICPwPBYNzDNNYI2ecFLQ/edit#gid=1592750376.

Is there a way how you could share with us what are you developing right now, what is the pipeline or plan for future updates?
Something like release plan for each week (just an idea)…

There is also no manual. For example for fanet usage or for vario sound tunner - it was shared only on the FB.

**Comment by fhorinek** [comment]
similar to
https://github.com/fhorinek/BB/issues/39
