### ISSUE TITLE
Unable to fully  charge Strato

### ISSUE THREAD

**Issue by kaja78** [fhorinek/BB#54]
I am able to charge my Strato only to 99%. So charging never stops in both slow as well fast mode.
Also I am not sure how this could affect battery life. Is it safe to let Strato charging couple of hours in "charging at 99% state" (i. e. overnight)?

**Comment by kaja78** [comment]
![image](https://user-images.githubusercontent.com/6780745/128517528-66c039ef-2c7b-4dfc-ac35-a56de7ff69d9.jpeg)

**Comment by stratobugs** [comment]
Same with me.

**Comment by Altgenug1** [comment]
And sometimes it reaches 98% and overnight it reduces to 95%

**Comment by fhorinek** [comment]
Check out new bootloader, it now stops the charging properly.
https://strato.skybean.eu/dfu/
