### ISSUE TITLE
[during flight] strato freeze when changing volume with pushing the button 

### ISSUE THREAD

**Issue by ukeconsulting** [fhorinek/BB#58]
FW140
easy to reproduce: 
manually start flight
go to sound menu and change the sound in pushing continuously the button left or right.
if it doesn't bug quick enough, move the vario up and down.

i did it simultaneously on both stratos they freezed quite at the same moment.

**Comment by fhorinek** [comment]
confirmed the command are going too fast to esp32, need to implement transmit buffer or some kind of protection

**Comment by fhorinek** [comment]
Fixed
