### ISSUE TITLE
[in flight] when listening music, the vario bips cut the music. 

### ISSUE THREAD

**Issue by ukeconsulting** [fhorinek/BB#59]
it is like the function of the vario sound and the function of the music are taking the output alternatively.

the smartphone is 10 cm far from the strato

Enhancements: 
- chosing the volume separately of BT and vario and general sound
- behing able to mute vario sound or the BT sound or both (menu and widget like with skydrop)

**Comment by Skyhighpara** [comment]
What's the lowest **possible** priority than can be assigned to an issue?

But seriously, it's hard to have a fluent alternating between different audio streams or perfect fusion of the 2. I do not think this will be a problem to address with any urgency.

**Comment by ukeconsulting** [comment]
it is a bug, i register it.
if you don't understand the point, it is your problem ^_^

**Comment by fhorinek** [comment]
All the report are useful, even the low priority one. Thank you!

**Comment by ukeconsulting** [comment]
you are welcome :-)
As a  BT speaker, out of flight, there is a 1s to 3s periodic blank (every about 90s ) when playing music. (i remarked it during home tests)

**Comment by ukeconsulting** [comment]
i didn't heard the issue since a long time, i think we can close it.
