### ISSUE TITLE
Battery discharges even if it is powered off

### ISSUE THREAD

**Issue by bjnord2** [fhorinek/BB#60]
Even if I power off the Strato, it discharges now and then. So it doesnt always turn off properly.

**Comment by Bosluis** [comment]
Had this once as well so far.

**Comment by ashghinn** [comment]
I can confirm discharge when Strato apparently switched off (fw 143). Also have had frequent problem this morning with audio emitting constant vario bleep after unit powered down (see attached video). In this mode it will not turn on using the power button but first  requires long pressing left and right arrows to restart.

**Comment by ashghinn** [comment]
https://user-images.githubusercontent.com/87761815/129381010-339d8fc4-c048-4e0f-bbed-628cb66f845d.mp4

**Comment by bjnord2** [comment]
Tried it today, and it worked fine for the 2hours30 minutes it was on, and it also seem to shut off properly.

**Comment by vojtechBohman** [comment]
I took the vario to the races and it burned me out pretty good. The claimed battery life doesn't match. I was sure the device was charged, but unfortunately it miraculously drained itself. 
When charging it never displays completed, still only 99%.
This has happened several times over the last 14 days.
It is unreliable and therefore useless.

When do you plan to have some basic, usable, debugged SW?
I'm considering a complaint and a refund.

**Comment by fhorinek** [comment]
It drained itself in power-off state?

Stability was increased quite a lot in recent releases and also the widget list is growing. 
Improved power management is the last missing piece now. The implementation for better power use, will be  done in next week.

**Comment by fhorinek** [comment]
This bug is fixed in 145+, If the problem reapers feel free to re-open the issue
