### ISSUE TITLE
Wifi stays on even when switched off

### ISSUE THREAD

**Issue by Bosluis** [fhorinek/BB#62]
FW 139
Played around with the my strato today. Presumably switched it off and upon grabbing my phone and trying to access a website it asks if I would like to switch to mobile usage or continue with my "Starto"  wifi even though its not connected to the Internet.
Switched to my home wifi. Even after 15 minute now I still see my "Strato" wifi.
Screen is black, tried switching the device on, no luck screen stays dead. 
Connected it to power outlet, no reaction from device.
Connected it to my pc with usb and power connect, no reaction from device.
 press Left, right plus power on button for 5 seconds, released and now device can be switche don using the power on button.

**Comment by fhorinek** [comment]
This bug is fixed in 145+, If the problem reapers feel free to re-open the issue
