### ISSUE TITLE
when powered off with BT playing music after flight , strato still play music with blank screen 

### ISSUE THREAD

**Issue by ukeconsulting** [fhorinek/BB#64]
FW143 i don't know if it is a feature. 
compulsory to make reset hardware to switch it off completely.
the normal power off by down button is not possible

**Comment by ashghinn** [comment]
This seems closely related to issues described in #61 "Battery discharges even if is powered off"

**Comment by ukeconsulting** [comment]
with FW145, power off stop the speaker on bluetooth too.

**Comment by fhorinek** [comment]
fixed, if the problem raise again please re-open
