### ISSUE TITLE
[ergonomy] the config settings are only recorded when powered off

### ISSUE THREAD

**Issue by ukeconsulting** [fhorinek/BB#65]
all FW until current 143.
as the config setting are recorded when powered off, each time you have to do an hard reset you lose all change made and it is really not confortable. 
the technic used now is to change settings, power off and then power on again.

it could be recorded when we leave the setting menu to the main vario display
(and every time you leave the wifi menu :-p )

**Comment by ukeconsulting** [comment]
so perhaps a safe start after reset ? (enable to load another configuration)

**Comment by fhorinek** [comment]
the goal is to not need to use hardware reset, what abut "store configuration" option in dev menu?

**Comment by ukeconsulting** [comment]
if it is easy to find/reach it is ok 
or perhaps on settings menu exit : do you want to save or not? 
for the wifi password you can save it immediatly since the bug on wifi password is nearly unprobable.

**Comment by fhorinek** [comment]
Wifi password is stored when you connect successfully to ap

**Comment by ukeconsulting** [comment]
strange: i already had to put again the same password a reboot with reset after trying to update with OTA, and i was connected before reset

**Comment by fhorinek** [comment]
the setting are now recorder after you leave the menu
