### ISSUE TITLE
physical confirmation on strato when connecting with BT to avoid hijacking. 

### ISSUE THREAD

**Issue by ukeconsulting** [fhorinek/BB#67]
with friends we like to hijack BT devices (even during flights, it is funny to put stupid music at good moments), with strato it is not possible to hijack BT music when it is already playing music but it is still possible to hijack when no phone is connected.
is it possible to add a BT confirmation menu (with 20s automatic refusal) on strato when a device try to connect to strato with BT ? so no hijack is possible.

**Comment by fhorinek** [comment]
similar to #68
I will add options to enable pairing only in menu, and few additional options

**Comment by ukeconsulting** [comment]
FW166: i tested some configuration (connection, saying no, automatic non confirmation), that works well, thanks.

a bonus can be to show the name and the BT ID of the hijacking device. 
but it is not important, the hijacking prevention is enough.

**Comment by fhorinek** [comment]
Currently the Bluetooth stack provide me only with the Mac address, the name is only handed to me after successful pairing. But the numerical comparison provide enough authentication for safe pairing. Also you can only see the strato if you are in Bluetooth settings.
Issue fixed, thank you for report
