### ISSUE TITLE
No bluetooth on/off switch under device settings. 

### ISSUE THREAD

**Issue by stratobugs** [fhorinek/BB#68]
No bluetooth on/off switch under device settings. 
Power saving and control of communication interface.

**Comment by ukeconsulting** [comment]
the bluetooth switch exist now and work but it bug: when disabling bluetooth disconnect the wifi from the AP (it reconnect itself after).

**Comment by fhorinek** [comment]
Yes this is known issue. Bug in the Bluetooth stack prevent me to properly shutdown the interface. My workaround is to reset whole ESP.
I consider it as a small problem for now. I will not fix this until the ESP stack fix the bug.
