### ISSUE TITLE
Sound freeze fw145

### ISSUE THREAD

**Issue by fliescher** [fhorinek/BB#72]
I don't know if it's related to #56 

Just after take off the Vario sound freezed. The device itself still worked normal (tracked the flight, showed the correct sink/climb rates on screen etc)

After landing I stopped the flight manually but the Vario still did this noise. The tone stopped after I turned the strato off.

**Comment by ukeconsulting** [comment]
i had quite this bug 2 times (FW somewhere between 133 and 140). i didn't try to change the volume, it didn't occure since.
for me the sound freeze but it was keeping "beep beep" just always the same. for you it was the sound freeze "beeeeeeep" or the sound boucle kept repeting like me?

**Comment by goodguy21** [comment]
For me it was a continuous beeeeeeeep. 
But I used my custom sound profile where it should do a continuous beep (while sinking). So I guess it's the same issue

**Comment by goodguy21** [comment]
Seems that it's the same as #56 
Had the same issue today during flight but in a more "dramatic" way. After approx 20 mins the Vario sound froze again, the Vario bar and values (avg and actual) died 5 mins later. After 38 mins of flight, all other values (compass arrow, speed, gps altitude and qnh altitude froze). Can't tell if it still tracked the flight until touchdown though. I'll check that later.

**Comment by Altgenug1** [comment]
Had the same issue today during flight. After the start the Vario sound froze (sink tone) After reboot it works for approximately 20 min, than again. Again reboot and again frozen sink tone after 10 to 20 min.

**Comment by fhorinek** [comment]
Fixed
