### ISSUE TITLE
calibration not working

### ISSUE THREAD

**Issue by rrunner83** [fhorinek/BB#73]
in order to use e.g. the compass widget I get the message "need calibration."
when starting calibration process in system menu following happens:
1. calibrating gyroscope -> ok
2. calibrating accelerometer (device portrait mode) -> ok
3. calibrating accelerometer (landscape mode) -> calibration will not start
   -> I tried several positions and took enough time, but it's not working

FW: all firmware from beginning on.
HW revision: 22

**Comment by stratobugs** [comment]
Same with me.

It does not proceede properly at different positions, always slightly different in each calibration process. In my case the problem occurs mostly when the instrument needs to lay "Display up"...that takes a long time until it proceeds to the next step "display down". Do not know if it takes the new value or just jumps to the next step in the process without saving the new value.

Finially the compass widget shows the correct direction. I do not know if other parameters go wrong.

**Comment by chrisyeh889** [comment]
I also Got this problem from time to time. have to reset more than once......

**Comment by atosmarkyp** [comment]
I've complained about this calibration issue continually since early June by email.  I have also reported an issue with the compass not working (No. 75) and have been advised to calibrate my unit.  I can't calibrate it.  It's doing exactly as reported by rrunner83 who has raised this calibration issue log.  I've tried reset many times, it will not work. Can someone please advise what is going on with this ?

**Comment by fhorinek** [comment]
We have replicate this issue on few of our devices. Currently we are implementing solution.

**Comment by rrunner83** [comment]
update with FW166:
calibrating is now working until the display shows "1Z" and I don't know how to proceed.
any instructions on this?

**Comment by fhorinek** [comment]
Can you please make a photo?

**Comment by rrunner83** [comment]
issue solved, I had to put the device once with display up and once display down. now calibration was successfull.

**Comment by atosmarkyp** [comment]
Hi Frantisek,

I see that this issue has been closed, I still have the issue.  I still
cannot calibrate my Strato.  Have you found a solution in the firmware that
is about to be rolled out ?

Thanks,

Mark.

**Comment by fhorinek** [comment]
The newest firmware should solve your issue. There are more tweaks in the next release, that will be released soon. I am reopening the issue until you are able to calibrate

**Comment by atosmarkyp** [comment]
Hi Frantisek,  Thank you for the quick reply.  I updated to FW166 tonight and ran the calibration cycle.  The device has calibrated perfectly ok.  I have observed that the device is also starting, operating and shutting off lots faster than it has done before.

Thanks,

Regards,

Mark
