### ISSUE TITLE
Occiasional Bus fault, update not working

### ISSUE THREAD

**Issue by TobiasWust** [fhorinek/BB#74]
![IMG_20210901_192911](https://user-images.githubusercontent.com/10038072/131717284-94085c66-9216-4403-9324-15b155ffd3d8.jpg)

Last time it happened when I tried to update from 143 to 148
Update is not working on my device
check for updates: connection timeout
install update: question "start update?" appears, but after ✔ nothing happens

**Comment by fhorinek** [comment]
I am working on the stability for OTA update right now. I'm the mean time you can download strato.fw from https://strato.skybean.eu/fw and place it directly to the device root via USB

**Comment by TobiasWust** [comment]
that way the update works 👍
