### ISSUE TITLE
Compass stopped working

### ISSUE THREAD

**Issue by atosmarkyp** [fhorinek/BB#75]
I did upgrade to FW148 yesterday and the compass was working great, all 3 widgets (compass arrow, compass heading and compass points.  But last night it stopped working correctly, if I rotate strato through 180 degrees the compass bearing numbers range from 86 to 107 degrees, the arrow points left incorrectly indicating that I'm continually pointing east, also compass points indicate continual east.  I've tried the reset, no difference, and can't calibrate the unit because it hangs in accelerometer Z+ calibration cycle.

**Comment by stratobugs** [comment]
With update to fw148 CovPass looses track. Not immediately after updating, but so,ehow next day. Calibration helps so far.

**Comment by atosmarkyp** [comment]
Calibration does not help my issue, as my unit won't calibrate.  As mentioned in issue log message, I cannot calibrate the unit because it hangs in accelerometer Z+ calibration cycle,.  Always has done since i've had it, I've reported it via e-mail several times, keep being told that you're working on a program fix.

**Comment by atosmarkyp** [comment]
Update FW166 has cured my compass problem.  It is working perfectly OK now.
