### ISSUE TITLE
Height above take-off

### ISSUE THREAD

**Issue by subpg** [fhorinek/BB#78]
Height above take-off showed negative, I had taken off from the grassy area in the foreground and was clearly above it.

![IMG_20210904_142026](https://user-images.githubusercontent.com/77536025/132120967-9cd7255f-be7d-4ae3-acb9-06cc304b65e3.jpg)

**Comment by dazdo** [comment]
Flight time shows 26 seconds in flight, so are you sure that strato launches at takeoff?
Anyway - Nice picture :) can we use it for social media?
Martin from SkyBean

**Comment by subpg** [comment]
Hi Martin,

I am pretty sure that the strato launched at take-off because I have the
vario silent unless in flight and it was working, but the flight time was
resetting because I had it set on height only.
You can use the image,, I tried to attached the original to this email, but
it's too large.

Thanks
Steve

**Comment by fhorinek** [comment]
So it will not reset if you enable ground speed checking for auto land?

**Comment by subpg** [comment]
Not sure, I will try to test and let you know.

**Comment by subpg** [comment]
Hi,

It happened again today, setting is Auto Landing: Altitude within +/-16ft and Speed <18.0km/h
[21.09.2021 09.45.igc.txt](https://github.com/fhorinek/BB/files/7205212/21.09.2021.09.45.igc.txt)
[21.09.2021 11.30.igc.txt](https://github.com/fhorinek/BB/files/7205214/21.09.2021.11.30.igc.txt)

I have attached the log files, I was probably about 300' above take-off but it was strong winds so my ground speed could have dropped below 18km but definitely not within +/-16'  of take-off.

Thanks Steve

**Comment by fhorinek** [comment]
Hi Steve, 

the Altitude within +/-16ft  means that device will autoland if you altitude will not change by that amount in specified timeout (default 30s) while your speed is less than 18km/h.

The device worked correctly, you did not change your altitude within last 30 seconds for more than +/-16ft, after the analysis of your flight record. I suggest to use smaller range for autoland.

Fero
