### ISSUE TITLE
Flight time kept resetting during flight

### ISSUE THREAD

**Issue by subpg** [fhorinek/BB#79]
Flight time would reset to zero and start counting again at random intervals during flight.
It was a coastal soaring flight with a constant ground speed (not gale hanging) and 20 - 100' height gains.

**Comment by fhorinek** [comment]
can you please provide the log for the flight to examine?

**Comment by fhorinek** [comment]
I guess this will be related to #78

**Comment by fhorinek** [comment]
Did you change the auto landing settings?

**Comment by subpg** [comment]
Hi,

I have just checked and the setting was set to '+/-16ft' so that was probably the problem.

Thanks
Steve
