### ISSUE TITLE
Battery losing capacity while charging

### ISSUE THREAD

**Issue by goodguy21** [fhorinek/BB#80]
I'm on fw148 currently and since yesterday it happens that Strato isn't charging but discharging when a charger is connected. Happens with various chargers and cables. Sometimes charging works normally.

The voltage of the battery does decrease in above stated example. E.g. it decreased from 4.17V to 4.13V (From 87% to 84%) while the original Strato/Skybean equipment was connected to charge (but it discharged).

**Comment by goodguy21** [comment]
Problem first occured when I changed to fw154. However switching to earlier fw (139, 145, 148) doesn't solve the issue. I think it's hardware based 😑
Any idea how I could check that?

**Comment by fhorinek** [comment]
The problem is rooted in the passthrough charging system. On some devices the two port controllers are fighting each other. We are working on the solution. It is software based

**Comment by fhorinek** [comment]
Check out new bootloader, it now stops the charging properly.
https://strato.skybean.eu/dfu/
