### ISSUE TITLE
molded case 

### ISSUE THREAD

**Issue by KrzysiekJ13** [fhorinek/BB#81]
Hi,
I've noted few days ago that glue has begun to dry and crumbled.
now, at the top of the device, there is a crack.
has anyone the same issue? can i put some glue there to fix it? 
![20210907_170705](https://user-images.githubusercontent.com/87690296/132461247-9240afde-c09f-4043-8e1c-dda4cea1ff5b.jpg)

**Comment by fhorinek** [comment]
please write a message to info@skybean.eu. They will handle your request
This page is used for software development, not customer support
