### ISSUE TITLE
power on/off button sequence

### ISSUE THREAD

**Issue by daricek** [fhorinek/BB#90]
power ON
- to prevent accidental power ON inside backpack - would be fine to must confirm by separate click of power button, the same like current power off sequence

power OFF
- the second way to perform power OFF may be just long press, e.g. 5s (the same like SkyDrop vario)
- disable standard power OFF sequence (pull menu + click) when flying to prevent accidental lost of tracklog

**Comment by ukeconsulting** [comment]
i confirm that the vario still on my cockpit powered once itself in the bag during a lift up.

**Comment by goodguy21** [comment]
Please also add a different activation sequence for the flashlight (and powerbank mode as well). Already happened several times that the flashlight was activated inside the bag. Drains the battery and the device gets very hot!

**Comment by rrunner83** [comment]
i also noticed that my strato turns on in the bag. it has something to do, in which direction you put the device in the case. there is a small zip handle inside, which is located direct on the power button und pushes it with low pressure from outside.

**Comment by goodguy21** [comment]
> i also noticed that my strato turns on in the bag. it has something to do, in which direction you put the device in the case. there is a small zip handle inside, which is located direct on the power button und pushes it with low pressure from outside.

I noticed that little zipper too. But for me it turns on independently in which way I put it in. To be fair, my hiking equipment is packed fairly stuffed.

**Comment by ukeconsulting** [comment]
> i also noticed that my strato turns on in the bag. it has something to do, in which direction you put the device in the case. there is a small zip handle inside, which is located direct on the power button und pushes it with low pressure from outside.

you have to put the back of the strato face the zipper, if not there is a risk of breaking the screen. 
the screen should always be front to the case side with nothing.

**Comment by fhorinek** [comment]
There is new power-on sequence implemented
https://strato.skybean.eu/dfu/
