### ISSUE TITLE
provide "default" pages with basic widgets

### ISSUE THREAD

**Issue by rrunner83** [fhorinek/BB#94]
it happened now several times, that after updating the firmware, the customized pages with the widgets are deleted.
for this issue I suppose to provide a basic page and widgets with every new firmware.

**Comment by ukeconsulting** [comment]
the problem is more that the update should not erase your pages oO

a temporary workaround is that you can save the page them with a usb wire to a computer and put them again. that doesn't solve anything but at least if you have a computer near you can save some time.

**Comment by fhorinek** [comment]
The update should not delete the custom pages. Also if you don't have any pages the strato will create the default one. Please send me your config directory.

**Comment by rrunner83** [comment]
<img width="663" alt="image" src="https://user-images.githubusercontent.com/18677538/135215424-67574fcc-f37d-400b-a542-e84a719e9792.png">

**Comment by fhorinek** [comment]
please send me zip file to fero@skybean.eu
